# Dependencies

markdown: kramdown
kramdown: 
  input: GFM
  toc_levels: 1..2
  # parse_block_html: true

# markdown: CommonMarkGhPages

highlighter:      rouge

# Permalinks
# permalink:        pretty

# Setup
title:            "Mini Fish"
tagline:          ''
description:      ''
url:              https://github.com/Jiayu-Tian
baseurl:          ''

author:
  name:           'Jiayu Tian'

paginate:         10
paginate_path:    "/blog/page:num/"

# Custom vars
# version:          2.1.0

github:           
  repo:           https://github.com/Jiayu-Tian

plugins: 
  - jekyll-paginate
  - jekyll-archives
  - jekyll-commonmark-ghpages

disqus:
  shortname: Mini-Fish
